name: Mirror multiple upstream repos to public forks

on:
  schedule:
    - cron: '0 6 * * *'   # 每天 Aisa/Shanghai 06:00 运行
  workflow_dispatch:

jobs:
  sync-system-prompts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/asgeirtj/system_prompts_leaks.git

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Push to public fork main
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Jackie264/system_prompts_leaks.git \
            refs/remotes/upstream/main:refs/heads/main --force

  sync-passwall-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/xiaorouji/openwrt-passwall-packages.git

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Push to public fork main
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Jackie264/openwrt-passwall-packages.git \
            refs/remotes/upstream/main:refs/heads/main --force

  sync-openwrt-passwall2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/xiaorouji/openwrt-passwall2.git

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Push to public fork main
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Jackie264/openwrt-passwall2.git \
            refs/remotes/upstream/main:refs/heads/main --force

  sync-ChatGPT-Micro-Cap-Experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/LuckyOne7777/ChatGPT-Micro-Cap-Experiment.git

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Push to public fork main
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Jackie264/ChatGPT-Micro-Cap-Experiment.git \
            refs/remotes/upstream/main:refs/heads/main --force
            
  sync-advanced-reboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/stangri/luci-app-advanced-reboot.git

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Push to public fork main
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Jackie264/luci-app-advanced-reboot.git \
            refs/remotes/upstream/main:refs/heads/main --force
