name: Mirror upstream to public fork

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 UTC 2:00 运行（北京时间 10:00）
  workflow_dispatch:       # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/asgeirtj/system_prompts_leaks.git

      - name: Fetch upstream main
        run: git fetch upstream main

      - name: Push upstream main to public fork main (mirror)
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Jackie264/system_prompts_leaks.git \
            refs/remotes/upstream/main:refs/heads/main --force
